// Generated by CoffeeScript 1.6.3
/*
* @author Andrew D.Laptev <a.d.laptev@gmail.com>
*/


/*global describe, beforeEach, afterEach, it*/


(function() {
  var BoobstSocket, assert, boobst;

  assert = require('assert');

  boobst = require('../boobst');

  BoobstSocket = boobst.BoobstSocket;

  describe('xecute', function() {
    var bs;
    bs = new BoobstSocket(require('./test.config'));
    beforeEach(function(done) {
      return bs.connect(function(err) {
        if (err) {
          throw err;
        }
        return done();
      });
    });
    afterEach(function(done) {
      return bs.disconnect(function() {
        return done();
      });
    });
    return describe('#run hello world', function() {
      return it('should properly switch between namespaces', function(done) {
        return bs.xecute('write "hello"', function(err, data) {
          console.log(data);
          assert.equal(err, null);
          assert.ok(data === 'hello' || data === 'disallowed');
          return done();
        });
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=test.xecute.map
*/
